import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedGamification() {
  console.log('🎮 Seeding gamification data...');

  // Badges
  const badges = [
    // Achievement badges
    {
      key: 'first_plan',
      name: 'İlk Plan',
      description: 'İlk planını oluşturdun!',
      icon: '📝',
      category: 'achievement' as const,
      rarity: 'common' as const,
      xpReward: 50,
      coinReward: 10,
      sortOrder: 1,
    },
    {
      key: 'first_recipe',
      name: 'İlk Tarif',
      description: 'İlk tarifini paylaştın!',
      icon: '👨‍🍳',
      category: 'achievement' as const,
      rarity: 'common' as const,
      xpReward: 50,
      coinReward: 10,
      sortOrder: 2,
    },
    {
      key: 'first_comment',
      name: 'İlk Yorum',
      description: 'İlk yorumunu yaptın!',
      icon: '💬',
      category: 'achievement' as const,
      rarity: 'common' as const,
      xpReward: 25,
      coinReward: 5,
      sortOrder: 3,
    },
    // Milestone badges
    {
      key: 'weight_loss_5kg',
      name: '5kg Kaybı',
      description: '5kg verdin, harikasın!',
      icon: '🎯',
      category: 'milestone' as const,
      rarity: 'rare' as const,
      xpReward: 100,
      coinReward: 25,
      sortOrder: 1,
    },
    {
      key: 'weight_loss_10kg',
      name: '10kg Kaybı',
      description: '10kg verdin, inanılmaz!',
      icon: '🏆',
      category: 'milestone' as const,
      rarity: 'epic' as const,
      xpReward: 200,
      coinReward: 50,
      sortOrder: 2,
    },
    {
      key: 'weight_loss_20kg',
      name: '20kg Kaybı',
      description: '20kg verdin, efsanesin!',
      icon: '👑',
      category: 'milestone' as const,
      rarity: 'legendary' as const,
      xpReward: 500,
      coinReward: 100,
      sortOrder: 3,
    },
    // Streak badges
    {
      key: 'streak_7',
      name: '7 Günlük Seri',
      description: '7 gün üst üste check-in yaptın!',
      icon: '🔥',
      category: 'milestone' as const,
      rarity: 'rare' as const,
      xpReward: 75,
      coinReward: 20,
      sortOrder: 4,
    },
    {
      key: 'streak_30',
      name: '30 Günlük Seri',
      description: '30 gün üst üste check-in yaptın!',
      icon: '⚡',
      category: 'milestone' as const,
      rarity: 'epic' as const,
      xpReward: 250,
      coinReward: 75,
      sortOrder: 5,
    },
    {
      key: 'streak_100',
      name: '100 Günlük Seri',
      description: '100 gün üst üste check-in yaptın!',
      icon: '💎',
      category: 'milestone' as const,
      rarity: 'legendary' as const,
      xpReward: 1000,
      coinReward: 250,
      sortOrder: 6,
    },
    // Social badges
    {
      key: 'social_10_followers',
      name: '10 Takipçi',
      description: '10 takipçiye ulaştın!',
      icon: '👥',
      category: 'social' as const,
      rarity: 'common' as const,
      xpReward: 50,
      coinReward: 10,
      sortOrder: 1,
    },
    {
      key: 'social_50_followers',
      name: '50 Takipçi',
      description: '50 takipçiye ulaştın!',
      icon: '🌟',
      category: 'social' as const,
      rarity: 'rare' as const,
      xpReward: 150,
      coinReward: 30,
      sortOrder: 2,
    },
    {
      key: 'social_100_likes',
      name: '100 Beğeni',
      description: 'İçeriklerine 100 beğeni aldın!',
      icon: '❤️',
      category: 'social' as const,
      rarity: 'rare' as const,
      xpReward: 100,
      coinReward: 25,
      sortOrder: 3,
    },
    // Special badges
    {
      key: 'early_adopter',
      name: 'Erken Katılan',
      description: 'Platformun ilk kullanıcılarındansın!',
      icon: '🚀',
      category: 'special' as const,
      rarity: 'legendary' as const,
      xpReward: 500,
      coinReward: 100,
      sortOrder: 1,
    },
    {
      key: 'guild_founder',
      name: 'Lonca Kurucusu',
      description: 'Bir lonca kurdun!',
      icon: '🏰',
      category: 'special' as const,
      rarity: 'epic' as const,
      xpReward: 200,
      coinReward: 50,
      sortOrder: 2,
    },
    
    // === TRACKING & HEALTH BADGES ===
    // Weight Tracking
    {
      key: 'first_weight_log',
      name: 'İlk Tartı',
      description: 'İlk kilo kaydını girdin!',
      icon: '⚖️',
      category: 'achievement' as const,
      rarity: 'common' as const,
      xpReward: 25,
      coinReward: 5,
      sortOrder: 4,
    },
    {
      key: 'weight_loss_1kg',
      name: 'İlk Kilo',
      description: 'İlk kilonu verdin!',
      icon: '🎈',
      category: 'milestone' as const,
      rarity: 'common' as const,
      xpReward: 50,
      coinReward: 10,
      sortOrder: 7,
    },
    {
      key: 'weight_loss_50kg',
      name: 'Süper Transformasyon',
      description: '50kg verdin, inanılmaz bir başarı!',
      icon: '🦸',
      category: 'milestone' as const,
      rarity: 'legendary' as const,
      xpReward: 2000,
      coinReward: 500,
      sortOrder: 8,
    },
    
    // Progress Photos
    {
      key: 'first_progress_photo',
      name: 'İlk Fotoğraf',
      description: 'İlk ilerleme fotoğrafını yükledin!',
      icon: '📸',
      category: 'achievement' as const,
      rarity: 'common' as const,
      xpReward: 30,
      coinReward: 10,
      sortOrder: 5,
    },
    {
      key: 'photo_streak_30',
      name: 'Fotoğraf Koleksiyoncusu',
      description: '30 gün boyunca fotoğraf çektin!',
      icon: '📷',
      category: 'milestone' as const,
      rarity: 'epic' as const,
      xpReward: 200,
      coinReward: 50,
      sortOrder: 9,
    },
    
    // Check-in
    {
      key: 'first_check_in',
      name: 'İlk Check-in',
      description: 'İlk günlük check-in\'ini yaptın!',
      icon: '✅',
      category: 'achievement' as const,
      rarity: 'common' as const,
      xpReward: 20,
      coinReward: 5,
      sortOrder: 6,
    },
    {
      key: 'streak_365',
      name: 'Yılın Şampiyonu',
      description: '365 gün üst üste check-in yaptın!',
      icon: '🏅',
      category: 'milestone' as const,
      rarity: 'legendary' as const,
      xpReward: 5000,
      coinReward: 1000,
      sortOrder: 10,
    },
    
    // Measurements & Mood
    {
      key: 'first_measurement',
      name: 'İlk Ölçüm',
      description: 'İlk vücut ölçümünü yaptın!',
      icon: '📏',
      category: 'achievement' as const,
      rarity: 'common' as const,
      xpReward: 25,
      coinReward: 5,
      sortOrder: 7,
    },
    {
      key: 'mood_tracker',
      name: 'Ruh Hali Takipçisi',
      description: '30 gün ruh hali kaydı tuttun!',
      icon: '😊',
      category: 'milestone' as const,
      rarity: 'rare' as const,
      xpReward: 100,
      coinReward: 25,
      sortOrder: 11,
    },
    
    // Voice Notes
    {
      key: 'first_voice_note',
      name: 'İlk Ses Notu',
      description: 'İlk ses notunu kaydettın!',
      icon: '🎙️',
      category: 'achievement' as const,
      rarity: 'common' as const,
      xpReward: 30,
      coinReward: 10,
      sortOrder: 8,
    },
    {
      key: 'voice_diary_master',
      name: 'Ses Günlüğü Ustası',
      description: '50 ses notu kaydettın!',
      icon: '🎧',
      category: 'milestone' as const,
      rarity: 'epic' as const,
      xpReward: 250,
      coinReward: 75,
      sortOrder: 12,
    },
    
    // === CONTENT CREATION BADGES ===
    // Recipes
    {
      key: 'recipe_master_10',
      name: 'Tarif Ustası',
      description: '10 tarif paylaştın!',
      icon: '👨‍🍳',
      category: 'achievement' as const,
      rarity: 'rare' as const,
      xpReward: 150,
      coinReward: 30,
      sortOrder: 9,
    },
    {
      key: 'recipe_master_50',
      name: 'Şef',
      description: '50 tarif paylaştın!',
      icon: '🧑‍🍳',
      category: 'achievement' as const,
      rarity: 'epic' as const,
      xpReward: 500,
      coinReward: 100,
      sortOrder: 10,
    },
    {
      key: 'recipe_viral',
      name: 'Viral Tarif',
      description: 'Tarifin 1000 beğeni aldı!',
      icon: '🔥',
      category: 'special' as const,
      rarity: 'legendary' as const,
      xpReward: 1000,
      coinReward: 250,
      sortOrder: 3,
    },
    
    // Plans
    {
      key: 'plan_creator_10',
      name: 'Plan Uzmanı',
      description: '10 plan oluşturdun!',
      icon: '📋',
      category: 'achievement' as const,
      rarity: 'rare' as const,
      xpReward: 150,
      coinReward: 30,
      sortOrder: 11,
    },
    {
      key: 'plan_popular',
      name: 'Popüler Plan',
      description: 'Planın 500 kişi tarafından kullanıldı!',
      icon: '⭐',
      category: 'special' as const,
      rarity: 'epic' as const,
      xpReward: 500,
      coinReward: 100,
      sortOrder: 4,
    },
    
    // Comments
    {
      key: 'comment_master_100',
      name: 'Yorum Ustası',
      description: '100 yorum yaptın!',
      icon: '💭',
      category: 'achievement' as const,
      rarity: 'rare' as const,
      xpReward: 100,
      coinReward: 25,
      sortOrder: 12,
    },
    {
      key: 'helpful_commenter',
      name: 'Yardımsever',
      description: 'Yorumların 100 beğeni aldı!',
      icon: '🤝',
      category: 'social' as const,
      rarity: 'rare' as const,
      xpReward: 150,
      coinReward: 30,
      sortOrder: 4,
    },
    
    // === SOCIAL & COMMUNITY BADGES ===
    // Followers
    {
      key: 'social_100_followers',
      name: '100 Takipçi',
      description: '100 takipçiye ulaştın!',
      icon: '🎯',
      category: 'social' as const,
      rarity: 'epic' as const,
      xpReward: 300,
      coinReward: 75,
      sortOrder: 5,
    },
    {
      key: 'social_500_followers',
      name: 'İnfluencer',
      description: '500 takipçiye ulaştın!',
      icon: '🌟',
      category: 'social' as const,
      rarity: 'legendary' as const,
      xpReward: 1000,
      coinReward: 250,
      sortOrder: 6,
    },
    {
      key: 'social_networker',
      name: 'Sosyal Kelebek',
      description: '50 kişiyi takip ettin!',
      icon: '🦋',
      category: 'social' as const,
      rarity: 'common' as const,
      xpReward: 50,
      coinReward: 10,
      sortOrder: 7,
    },
    
    // Groups
    {
      key: 'first_group_join',
      name: 'Grup Üyesi',
      description: 'İlk gruba katıldın!',
      icon: '👥',
      category: 'social' as const,
      rarity: 'common' as const,
      xpReward: 25,
      coinReward: 5,
      sortOrder: 8,
    },
    {
      key: 'group_creator',
      name: 'Grup Kurucusu',
      description: 'Bir grup oluşturdun!',
      icon: '🏛️',
      category: 'social' as const,
      rarity: 'rare' as const,
      xpReward: 100,
      coinReward: 25,
      sortOrder: 9,
    },
    {
      key: 'group_active_member',
      name: 'Aktif Üye',
      description: 'Gruplarda 100 gönderi paylaştın!',
      icon: '📢',
      category: 'social' as const,
      rarity: 'epic' as const,
      xpReward: 200,
      coinReward: 50,
      sortOrder: 10,
    },
    
    // Guild
    {
      key: 'guild_member',
      name: 'Lonca Üyesi',
      description: 'Bir loncaya katıldın!',
      icon: '⚔️',
      category: 'social' as const,
      rarity: 'common' as const,
      xpReward: 50,
      coinReward: 10,
      sortOrder: 11,
    },
    {
      key: 'guild_officer',
      name: 'Lonca Subayı',
      description: 'Lonca subayı oldun!',
      icon: '🛡️',
      category: 'special' as const,
      rarity: 'epic' as const,
      xpReward: 300,
      coinReward: 75,
      sortOrder: 5,
    },
    {
      key: 'guild_champion',
      name: 'Lonca Şampiyonu',
      description: 'Loncan 1. lige çıktı!',
      icon: '🏆',
      category: 'special' as const,
      rarity: 'legendary' as const,
      xpReward: 1000,
      coinReward: 250,
      sortOrder: 6,
    },
    
    // Messages
    {
      key: 'first_message',
      name: 'İlk Mesaj',
      description: 'İlk mesajını gönderdin!',
      icon: '✉️',
      category: 'social' as const,
      rarity: 'common' as const,
      xpReward: 20,
      coinReward: 5,
      sortOrder: 12,
    },
    {
      key: 'social_butterfly',
      name: 'Sohbet Canavarı',
      description: '100 mesaj gönderdin!',
      icon: '💌',
      category: 'social' as const,
      rarity: 'rare' as const,
      xpReward: 100,
      coinReward: 25,
      sortOrder: 13,
    },
    
    // Referrals
    {
      key: 'first_referral',
      name: 'İlk Davet',
      description: 'İlk arkadaşını davet ettin!',
      icon: '🎁',
      category: 'social' as const,
      rarity: 'common' as const,
      xpReward: 50,
      coinReward: 10,
      sortOrder: 14,
    },
    {
      key: 'referral_master_10',
      name: 'Davet Ustası',
      description: '10 arkadaşını davet ettin!',
      icon: '🎉',
      category: 'social' as const,
      rarity: 'epic' as const,
      xpReward: 500,
      coinReward: 100,
      sortOrder: 15,
    },
    {
      key: 'referral_legend',
      name: 'Davet Efsanesi',
      description: '50 arkadaşını davet ettin!',
      icon: '👑',
      category: 'social' as const,
      rarity: 'legendary' as const,
      xpReward: 2000,
      coinReward: 500,
      sortOrder: 16,
    },
    
    // === GAMIFICATION BADGES ===
    // Levels
    {
      key: 'level_10',
      name: 'Seviye 10',
      description: '10. seviyeye ulaştın!',
      icon: '🔟',
      category: 'milestone' as const,
      rarity: 'rare' as const,
      xpReward: 100,
      coinReward: 25,
      sortOrder: 13,
    },
    {
      key: 'level_25',
      name: 'Seviye 25',
      description: '25. seviyeye ulaştın!',
      icon: '🎖️',
      category: 'milestone' as const,
      rarity: 'epic' as const,
      xpReward: 250,
      coinReward: 75,
      sortOrder: 14,
    },
    {
      key: 'level_50',
      name: 'Seviye 50',
      description: '50. seviyeye ulaştın!',
      icon: '👑',
      category: 'milestone' as const,
      rarity: 'legendary' as const,
      xpReward: 1000,
      coinReward: 250,
      sortOrder: 15,
    },
    {
      key: 'level_100',
      name: 'Efsane',
      description: '100. seviyeye ulaştın!',
      icon: '💎',
      category: 'milestone' as const,
      rarity: 'legendary' as const,
      xpReward: 5000,
      coinReward: 1000,
      sortOrder: 16,
    },
    
    // Quests
    {
      key: 'quest_master_10',
      name: 'Görev Tamamlayıcı',
      description: '10 görev tamamladın!',
      icon: '📝',
      category: 'achievement' as const,
      rarity: 'common' as const,
      xpReward: 50,
      coinReward: 10,
      sortOrder: 13,
    },
    {
      key: 'quest_master_100',
      name: 'Görev Ustası',
      description: '100 görev tamamladın!',
      icon: '📜',
      category: 'achievement' as const,
      rarity: 'epic' as const,
      xpReward: 500,
      coinReward: 100,
      sortOrder: 14,
    },
    {
      key: 'daily_quest_streak_30',
      name: 'Günlük Görev Şampiyonu',
      description: '30 gün üst üste günlük görevleri tamamladın!',
      icon: '🎯',
      category: 'milestone' as const,
      rarity: 'epic' as const,
      xpReward: 300,
      coinReward: 75,
      sortOrder: 17,
    },
    
    // Coins & Shop
    {
      key: 'coin_collector_1000',
      name: 'Coin Koleksiyoncusu',
      description: '1000 coin biriktirdin!',
      icon: '💰',
      category: 'milestone' as const,
      rarity: 'rare' as const,
      xpReward: 100,
      coinReward: 50,
      sortOrder: 18,
    },
    {
      key: 'coin_collector_10000',
      name: 'Zengin',
      description: '10000 coin biriktirdin!',
      icon: '💎',
      category: 'milestone' as const,
      rarity: 'legendary' as const,
      xpReward: 1000,
      coinReward: 250,
      sortOrder: 19,
    },
    {
      key: 'first_purchase',
      name: 'İlk Alışveriş',
      description: 'Mağazadan ilk alışverişini yaptın!',
      icon: '🛒',
      category: 'achievement' as const,
      rarity: 'common' as const,
      xpReward: 25,
      coinReward: 5,
      sortOrder: 15,
    },
    {
      key: 'shopaholic',
      name: 'Alışveriş Tutkunu',
      description: 'Mağazadan 20 ürün aldın!',
      icon: '🛍️',
      category: 'achievement' as const,
      rarity: 'rare' as const,
      xpReward: 150,
      coinReward: 30,
      sortOrder: 16,
    },
    
    // Leagues
    {
      key: 'league_bronze',
      name: 'Bronz Lig',
      description: 'Bronz lige ulaştın!',
      icon: '🥉',
      category: 'milestone' as const,
      rarity: 'common' as const,
      xpReward: 50,
      coinReward: 10,
      sortOrder: 20,
    },
    {
      key: 'league_silver',
      name: 'Gümüş Lig',
      description: 'Gümüş lige ulaştın!',
      icon: '🥈',
      category: 'milestone' as const,
      rarity: 'rare' as const,
      xpReward: 100,
      coinReward: 25,
      sortOrder: 21,
    },
    {
      key: 'league_gold',
      name: 'Altın Lig',
      description: 'Altın lige ulaştın!',
      icon: '🥇',
      category: 'milestone' as const,
      rarity: 'epic' as const,
      xpReward: 250,
      coinReward: 75,
      sortOrder: 22,
    },
    {
      key: 'league_platinum',
      name: 'Platin Lig',
      description: 'Platin lige ulaştın!',
      icon: '💿',
      category: 'milestone' as const,
      rarity: 'epic' as const,
      xpReward: 500,
      coinReward: 100,
      sortOrder: 23,
    },
    {
      key: 'league_diamond',
      name: 'Elmas Lig',
      description: 'Elmas lige ulaştın!',
      icon: '💎',
      category: 'milestone' as const,
      rarity: 'legendary' as const,
      xpReward: 1000,
      coinReward: 250,
      sortOrder: 24,
    },
    {
      key: 'season_winner',
      name: 'Sezon Şampiyonu',
      description: 'Bir sezonu 1. sırada bitirdin!',
      icon: '🏆',
      category: 'special' as const,
      rarity: 'legendary' as const,
      xpReward: 2000,
      coinReward: 500,
      sortOrder: 7,
    },
    
    // === SPECIAL EVENT BADGES ===
    {
      key: 'beta_tester',
      name: 'Beta Tester',
      description: 'Beta döneminde katıldın!',
      icon: '🧪',
      category: 'special' as const,
      rarity: 'legendary' as const,
      xpReward: 1000,
      coinReward: 250,
      sortOrder: 8,
    },
    {
      key: 'bug_hunter',
      name: 'Bug Avcısı',
      description: '10 bug rapor ettin!',
      icon: '🐛',
      category: 'special' as const,
      rarity: 'epic' as const,
      xpReward: 500,
      coinReward: 100,
      sortOrder: 9,
    },
    {
      key: 'community_hero',
      name: 'Topluluk Kahramanı',
      description: 'Topluluk moderatörü oldun!',
      icon: '🦸‍♂️',
      category: 'special' as const,
      rarity: 'legendary' as const,
      xpReward: 1000,
      coinReward: 250,
      sortOrder: 10,
    },
    {
      key: 'verified_user',
      name: 'Onaylı Kullanıcı',
      description: 'Hesabın onaylandı!',
      icon: '✓',
      category: 'special' as const,
      rarity: 'rare' as const,
      xpReward: 100,
      coinReward: 25,
      sortOrder: 11,
    },
    
    // === CONFESSION WALL BADGES ===
    {
      key: 'confession_first',
      name: 'Dürüst Ruh',
      description: 'İlk itirafını yaptın!',
      icon: '🙏',
      category: 'achievement' as const,
      rarity: 'common' as const,
      xpReward: 50,
      coinReward: 10,
      sortOrder: 17,
    },
    {
      key: 'confession_master',
      name: 'İtiraf Ustası',
      description: '10 itiraf yaptın!',
      icon: '📿',
      category: 'achievement' as const,
      rarity: 'rare' as const,
      xpReward: 150,
      coinReward: 50,
      sortOrder: 18,
    },
    {
      key: 'empathy_hero',
      name: 'Empati Kahramanı',
      description: '50 kez empati gösterdin!',
      icon: '💝',
      category: 'social' as const,
      rarity: 'epic' as const,
      xpReward: 200,
      coinReward: 50,
      sortOrder: 17,
    },
    {
      key: 'night_warrior',
      name: 'Gece Savaşçısı',
      description: 'Gece saatlerinde itiraf yaptın!',
      icon: '🌙',
      category: 'special' as const,
      rarity: 'rare' as const,
      xpReward: 100,
      coinReward: 25,
      sortOrder: 12,
    },
    {
      key: 'seasonal_ramadan',
      name: 'Ramazan Mücahidi',
      description: 'Ramazan ayında itiraf yaptın!',
      icon: '🌙',
      category: 'special' as const,
      rarity: 'epic' as const,
      xpReward: 150,
      coinReward: 40,
      sortOrder: 13,
    },
    {
      key: 'seasonal_newyear',
      name: 'Yılbaşı Kurbanı',
      description: 'Yılbaşı döneminde itiraf yaptın!',
      icon: '🎄',
      category: 'special' as const,
      rarity: 'epic' as const,
      xpReward: 150,
      coinReward: 40,
      sortOrder: 14,
    },
    {
      key: 'seasonal_bayram',
      name: 'Bayram Şekeri Avcısı',
      description: 'Bayram döneminde itiraf yaptın!',
      icon: '🍬',
      category: 'special' as const,
      rarity: 'epic' as const,
      xpReward: 150,
      coinReward: 40,
      sortOrder: 15,
    },
    {
      key: 'popular_confession',
      name: 'Viral İtiraf',
      description: 'İtirafın 100+ empati aldı!',
      icon: '🔥',
      category: 'special' as const,
      rarity: 'legendary' as const,
      xpReward: 500,
      coinReward: 100,
      sortOrder: 16,
    },
  ];

  for (const badge of badges) {
    await prisma.badge.upsert({
      where: { key: badge.key },
      update: badge,
      create: badge,
    });
  }

  console.log(`✅ Created ${badges.length} badges`);

  // Daily Quests
  const quests = [
    {
      key: 'daily_check_in',
      title: 'Günlük Check-in',
      description: 'Bugün check-in yap',
      icon: '✅',
      xpReward: 10,
      coinReward: 5,
      type: 'daily' as const,
      target: 1,
      sortOrder: 1,
    },
    {
      key: 'daily_weigh_in',
      title: 'Bugün Tartıl',
      description: 'Kilonu kaydet',
      icon: '⚖️',
      xpReward: 15,
      coinReward: 5,
      type: 'daily' as const,
      target: 1,
      sortOrder: 2,
    },
    {
      key: 'daily_water',
      title: 'Su İç',
      description: '8 bardak su iç',
      icon: '💧',
      xpReward: 10,
      coinReward: 5,
      type: 'daily' as const,
      target: 8,
      sortOrder: 3,
    },
    {
      key: 'daily_comment',
      title: 'Yorum Yap',
      description: 'Bir içeriğe yorum yap',
      icon: '💬',
      xpReward: 10,
      coinReward: 5,
      type: 'daily' as const,
      target: 1,
      sortOrder: 4,
    },
    {
      key: 'daily_like',
      title: 'Beğen',
      description: '3 içeriği beğen',
      icon: '❤️',
      xpReward: 10,
      coinReward: 5,
      type: 'daily' as const,
      target: 3,
      sortOrder: 5,
    },
  ];

  for (const quest of quests) {
    await prisma.dailyQuest.upsert({
      where: { key: quest.key },
      update: quest,
      create: quest,
    });
  }

  console.log(`✅ Created ${quests.length} quests`);

  // Shop Items
  const shopItems = [
    // Cosmetic items
    {
      key: 'avatar_frame_gold',
      name: 'Altın Çerçeve',
      description: 'Profiline altın çerçeve ekle',
      icon: '🖼️',
      category: 'cosmetic' as const,
      price: 100,
      stock: null,
      sortOrder: 1,
    },
    {
      key: 'profile_theme_dark',
      name: 'Karanlık Tema',
      description: 'Özel karanlık profil teması',
      icon: '🌙',
      category: 'cosmetic' as const,
      price: 50,
      stock: null,
      sortOrder: 2,
    },
    {
      key: 'badge_showcase',
      name: 'Rozet Vitrini',
      description: 'Profilinde 10 rozet göster',
      icon: '🏆',
      category: 'cosmetic' as const,
      price: 150,
      stock: null,
      sortOrder: 3,
    },
    // Boost items
    {
      key: 'xp_boost_2x',
      name: '2x XP Boost',
      description: '24 saat boyunca 2x XP kazan',
      icon: '⚡',
      category: 'boost' as const,
      price: 200,
      stock: null,
      sortOrder: 1,
    },
    {
      key: 'coin_boost_2x',
      name: '2x Coin Boost',
      description: '24 saat boyunca 2x coin kazan',
      icon: '💰',
      category: 'boost' as const,
      price: 200,
      stock: null,
      sortOrder: 2,
    },
    // Recovery items
    {
      key: 'streak_freeze',
      name: 'Seri Dondurma',
      description: '1 gün seri kaybını engelle',
      icon: '❄️',
      category: 'recovery' as const,
      price: 50,
      stock: null,
      sortOrder: 1,
    },
  ];

  for (const item of shopItems) {
    await prisma.shopItem.upsert({
      where: { key: item.key },
      update: item,
      create: item,
    });
  }

  console.log(`✅ Created ${shopItems.length} shop items`);

  // Create a sample season
  const now = new Date();
  const seasonStart = new Date(now.getFullYear(), now.getMonth(), 1);
  const seasonEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0);

  const season = await prisma.season.upsert({
    where: { id: 'season-2024-01' },
    update: {
      name: `${now.toLocaleString('tr-TR', { month: 'long' })} ${now.getFullYear()}`,
      startDate: seasonStart,
      endDate: seasonEnd,
      isActive: true,
    },
    create: {
      id: 'season-2024-01',
      name: `${now.toLocaleString('tr-TR', { month: 'long' })} ${now.getFullYear()}`,
      description: 'İlk sezon!',
      startDate: seasonStart,
      endDate: seasonEnd,
      isActive: true,
    },
  });

  console.log(`✅ Created season: ${season.name}`);

  // Create leagues for the season
  const leagues = [
    { tier: 'bronze' as const, name: 'Bronz Ligi', minPoints: 0, maxPoints: 999 },
    { tier: 'silver' as const, name: 'Gümüş Ligi', minPoints: 1000, maxPoints: 2499 },
    { tier: 'gold' as const, name: 'Altın Ligi', minPoints: 2500, maxPoints: 4999 },
    { tier: 'platinum' as const, name: 'Platin Ligi', minPoints: 5000, maxPoints: 9999 },
    { tier: 'diamond' as const, name: 'Elmas Ligi', minPoints: 10000, maxPoints: null },
  ];

  for (const league of leagues) {
    await prisma.league.upsert({
      where: {
        seasonId_tier: {
          seasonId: season.id,
          tier: league.tier as any,
        },
      },
      update: league,
      create: {
        ...league,
        seasonId: season.id,
      },
    });
  }

  console.log(`✅ Created ${leagues.length} leagues`);

  console.log('🎮 Gamification seeding completed!');
}

// Run if called directly
if (require.main === module) {
  seedGamification()
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
