import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function seedSinBadges() {
  console.log('🏆 Seeding sin badges...');

  const badges = [
    {
      key: 'first_sin',
      name: 'İlk Günah',
      description: 'İlk günah kaydını oluşturdun! Dürüst olmak önemli.',
      icon: '🍕',
      requirement: 'İlk günah kaydını oluştur',
      sinType: null,
      xpReward: 50,
      coinReward: 20,
      isActive: true,
      sortOrder: 1,
    },
    {
      key: 'sin_master',
      name: 'Günah Ustası',
      description: '10 günah kaydı oluşturdun. Takip etmeye devam!',
      icon: '📊',
      requirement: '10 günah kaydı oluştur',
      sinType: null,
      xpReward: 100,
      coinReward: 50,
      isActive: true,
      sortOrder: 2,
    },
    {
      key: 'honest_writer',
      name: 'Dürüst Yazar',
      description: '50 günah kaydı oluşturdun. Dürüstlük ödüllendirilir!',
      icon: '✍️',
      requirement: '50 günah kaydı oluştur',
      sinType: null,
      xpReward: 200,
      coinReward: 100,
      isActive: true,
      sortOrder: 3,
    },
    {
      key: 'transparency_champion',
      name: 'Şeffaflık Şampiyonu',
      description: '100 günah kaydı oluşturdun. İnanılmaz dürüstlük!',
      icon: '🏆',
      requirement: '100 günah kaydı oluştur',
      sinType: null,
      xpReward: 500,
      coinReward: 250,
      isActive: true,
      sortOrder: 4,
    },
    {
      key: 'calorie_hunter',
      name: 'Kalori Avcısı',
      description: 'Toplam 10.000+ kalori kaydettin.',
      icon: '🎯',
      requirement: 'Toplam 10000+ kalori kaydet',
      sinType: null,
      xpReward: 150,
      coinReward: 75,
      isActive: true,
      sortOrder: 5,
    },
    {
      key: 'weekend_warrior',
      name: 'Hafta Sonu Savaşçısı',
      description: 'Hafta sonu en az 3 günah kaydı oluşturdun.',
      icon: '⚔️',
      requirement: 'Hafta sonu 3+ günah kaydı oluştur',
      sinType: null,
      xpReward: 100,
      coinReward: 50,
      isActive: true,
      sortOrder: 6,
    },
    {
      key: 'night_guardian',
      name: 'Gece Bekçisi',
      description: 'Gece yarısı sonrası 10 günah kaydı oluşturdun.',
      icon: '🌙',
      requirement: '00:00-06:00 arası 10 günah kaydı oluştur',
      sinType: null,
      xpReward: 80,
      coinReward: 40,
      isActive: true,
      sortOrder: 7,
    },
    {
      key: 'holiday_hero',
      name: 'Tatil Günü Kahramanı',
      description: 'Bayram veya tatil günlerinde günah kaydı oluşturdun.',
      icon: '🦸',
      requirement: 'Tatil gününde günah kaydı oluştur',
      sinType: null,
      xpReward: 150,
      coinReward: 75,
      isActive: true,
      sortOrder: 8,
    },
    {
      key: 'super_honest',
      name: 'Süper Dürüst',
      description: '7 gün üst üste günah kaydı oluşturdun.',
      icon: '💪',
      requirement: '7 gün üst üste günah kaydı oluştur',
      sinType: null,
      xpReward: 200,
      coinReward: 100,
      isActive: true,
      sortOrder: 9,
    },
    {
      key: 'fast_food_hunter',
      name: 'Fast Food Avcısı',
      description: '20+ fast food kaydı oluşturdun.',
      icon: '🍔',
      requirement: '20+ fast food kaydı oluştur',
      sinType: 'fastfood' as const,
      xpReward: 100,
      coinReward: 50,
      isActive: true,
      sortOrder: 10,
    },
    {
      key: 'sweet_passion',
      name: 'Tatlı Tutkusu',
      description: '30+ tatlı/şeker kaydı oluşturdun.',
      icon: '🍰',
      requirement: '30+ tatlı/şeker kaydı oluştur',
      sinType: 'tatli' as const,
      xpReward: 120,
      coinReward: 60,
      isActive: true,
      sortOrder: 11,
    },
    {
      key: 'drink_tracker',
      name: 'İçecek İzleyicisi',
      description: '25+ şekerli içecek kaydı oluşturdun.',
      icon: '🥤',
      requirement: '25+ şekerli içecek kaydı oluştur',
      sinType: 'gazli' as const,
      xpReward: 100,
      coinReward: 50,
      isActive: true,
      sortOrder: 12,
    },
    {
      key: 'chocolate_detective',
      name: 'Çikolata Dedektifi',
      description: '15+ çikolata/kakao ürünü kaydı oluşturdun.',
      icon: '🍫',
      requirement: '15+ çikolata kaydı oluştur',
      sinType: 'tatli' as const,
      xpReward: 90,
      coinReward: 45,
      isActive: true,
      sortOrder: 13,
    },
    {
      key: 'snack_expert',
      name: 'Atıştırma Uzmanı',
      description: '40+ cips/atıştırmalık kaydı oluşturdun.',
      icon: '🥨',
      requirement: '40+ atıştırmalık kaydı oluştur',
      sinType: 'diger' as const,
      xpReward: 110,
      coinReward: 55,
      isActive: true,
      sortOrder: 14,
    },
    {
      key: 'breakfast_critic',
      name: 'Kahvaltı Eleştirmeni',
      description: '20+ kahvaltı günah kaydı oluşturdun.',
      icon: '🍳',
      requirement: '20+ kahvaltı günah kaydı oluştur',
      sinType: 'diger' as const,
      xpReward: 90,
      coinReward: 45,
      isActive: true,
      sortOrder: 15,
    },
    {
      key: 'dinner_observer',
      name: 'Akşam Yemeği Gözlemcisi',
      description: '30+ akşam yemeği günah kaydı oluşturdun.',
      icon: '🍽️',
      requirement: '30+ akşam yemeği günah kaydı oluştur',
      sinType: 'diger' as const,
      xpReward: 100,
      coinReward: 50,
      isActive: true,
      sortOrder: 16,
    },
    {
      key: 'social_eating_recorder',
      name: 'Sosyal Yemek Kaydedicisi',
      description: '10+ restoran/dışarıda yenen günah kaydı oluşturdun.',
      icon: '🍴',
      requirement: '10+ restoran günah kaydı oluştur',
      sinType: 'diger' as const,
      xpReward: 120,
      coinReward: 60,
      isActive: true,
      sortOrder: 17,
    },
    {
      key: 'weekly_summary_master',
      name: 'Haftalık Özet Ustası',
      description: 'Haftalık özetinde en az 20 günah kaydı vardı.',
      icon: '📈',
      requirement: 'Bir haftada 20+ günah kaydı oluştur',
      sinType: null,
      xpReward: 150,
      coinReward: 75,
      isActive: true,
      sortOrder: 18,
    },
    {
      key: 'monthly_stats_king',
      name: 'Aylık İstatistik Kralı',
      description: 'Bir ayda 100+ günah kaydı oluşturdun.',
      icon: '👑',
      requirement: 'Bir ayda 100+ günah kaydı oluştur',
      sinType: null,
      xpReward: 300,
      coinReward: 150,
      isActive: true,
      sortOrder: 19,
    },
    {
      key: 'detail_enthusiast',
      name: 'Detay Meraklısı',
      description: '50+ fotoğraflı günah kaydı oluşturdun.',
      icon: '📸',
      requirement: '50+ fotoğraflı günah kaydı oluştur',
      sinType: null,
      xpReward: 150,
      coinReward: 75,
      isActive: true,
      sortOrder: 20,
    },
    {
      key: 'reaction_collector',
      name: 'Reaksiyon Toplayıcı',
      description: '100+ reaksiyon aldın.',
      icon: '❤️',
      requirement: '100+ reaksiyon al',
      sinType: null,
      xpReward: 200,
      coinReward: 100,
      isActive: true,
      sortOrder: 21,
    },
    {
      key: 'comment_master',
      name: 'Yorum Ustası',
      description: '50+ yorum aldın.',
      icon: '💬',
      requirement: '50+ yorum al',
      sinType: null,
      xpReward: 150,
      coinReward: 75,
      isActive: true,
      sortOrder: 22,
    },
    {
      key: 'challenge_completer',
      name: 'Challenge Tamamlayıcı',
      description: '5 challenge tamamladın.',
      icon: '🎖️',
      requirement: '5 challenge tamamla',
      sinType: null,
      xpReward: 250,
      coinReward: 125,
      isActive: true,
      sortOrder: 23,
    },
    {
      key: 'sin_legend',
      name: 'Günah Efsanesi',
      description: '500+ günah kaydı oluşturdun. Efsanesin!',
      icon: '⭐',
      requirement: '500+ günah kaydı oluştur',
      sinType: null,
      xpReward: 1000,
      coinReward: 500,
      isActive: true,
      sortOrder: 24,
    },
  ];

  for (const badge of badges) {
    await prisma.sinBadge.create({
      data: badge,
    });
    console.log(`✅ Badge created: ${badge.name} ${badge.icon}`);
  }

  console.log('🎉 Sin badges seeded successfully!');
  console.log(`📊 Total badges: ${badges.length}`);
}

seedSinBadges()
  .catch((e) => {
    console.error('❌ Error seeding sin badges:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
